import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/navbar";
import styles from './index.module.css';
import Hero from "./_components/hero/hero";
import Footer from "./_components/footer";
import Waitlist from "./_components/waitlist";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MGZN",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.rootlayout}>
          <div className={styles.navbar}>
            {/* <Navbar /> */}
            <Waitlist />
          </div>
          <div className={styles.content}>
            {children}
          </div>
          <div>
            {/* <Footer /> */}
          </div>
        </div>
      </body>
    </html>
  );
}
