import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar";
import styles from './index.module.css';
import Hero from "./_components/hero";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.container}>
          <div className={styles.navbar}>
            <Navbar />
          </div>
          <div className={styles.content}>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
